import 'package:flutter/material.dart';
import 'theme/tailwind_theme.dart';

final List<Map<String, dynamic>> class10Subjects = [
  {'name': 'Science', 'icon': Icons.science, 'color': Tailwind.emerald500},
  {'name': 'Maths', 'icon': Icons.calculate, 'color': Tailwind.indigo500},
  {'name': 'Social', 'icon': Icons.public, 'color': Tailwind.amber500},
  {'name': 'English', 'icon': Icons.language, 'color': Tailwind.rose500},
];

final List<Map<String, dynamic>> class12Subjects = [
  {'name': 'Accountancy', 'icon': Icons.account_balance, 'color': Tailwind.blue500},
  {'name': 'Advance Tamil', 'icon': Icons.language, 'color': Tailwind.rose500},
  {'name': 'Auditing', 'icon': Icons.fact_check, 'color': Tailwind.teal500},
  {'name': 'Basic Automobile Engineering', 'icon': Icons.directions_car, 'color': Tailwind.slate500},
  {'name': 'Basic Civil Engineering', 'icon': Icons.architecture, 'color': Tailwind.orange500},
  {'name': 'Basic Electrical Engineering', 'icon': Icons.electrical_services, 'color': Tailwind.yellow500},
  {'name': 'Basic Electronics Engineering', 'icon': Icons.memory, 'color': Tailwind.indigo500},
  {'name': 'Basic Mechanical Engineering', 'icon': Icons.settings, 'color': Tailwind.slate600},
  {'name': 'Bio Botany', 'icon': Icons.park, 'color': Tailwind.emerald500},
  {'name': 'Bio Chemistry', 'icon': Icons.science, 'color': Tailwind.cyan500},
  {'name': 'Bio Zoology', 'icon': Icons.pets, 'color': Tailwind.green500},
  {'name': 'Botany', 'icon': Icons.local_florist, 'color': Tailwind.emerald400},
  {'name': 'Business Mathematics and Statistics', 'icon': Icons.bar_chart, 'color': Tailwind.indigo400},
  {'name': 'Chemistry Volume 1', 'icon': Icons.science, 'color': Tailwind.cyan600},
  {'name': 'Chemistry Volume 2', 'icon': Icons.science, 'color': Tailwind.cyan700},
  {'name': 'Commerce', 'icon': Icons.store, 'color': Tailwind.blue600},
  {'name': 'Communicative English', 'icon': Icons.record_voice_over, 'color': Tailwind.rose400},
  {'name': 'Computer Applications', 'icon': Icons.computer, 'color': Tailwind.purple500},
  {'name': 'Computer Science', 'icon': Icons.code, 'color': Tailwind.purple600},
  {'name': 'Economics', 'icon': Icons.trending_up, 'color': Tailwind.amber600},
  {'name': 'Employability Skills', 'icon': Icons.work, 'color': Tailwind.slate700},
  {'name': 'English', 'icon': Icons.language, 'color': Tailwind.rose500},
  {'name': 'Food Service Management', 'icon': Icons.restaurant, 'color': Tailwind.orange400},
  {'name': 'General Nursing', 'icon': Icons.local_hospital, 'color': Tailwind.red500},
  {'name': 'Geography', 'icon': Icons.map, 'color': Tailwind.green600},
  {'name': 'History', 'icon': Icons.history_edu, 'color': Tailwind.amber700},
  {'name': 'Home Science', 'icon': Icons.home, 'color': Tailwind.pink500},
  {'name': 'Mathematics Volume 1', 'icon': Icons.calculate, 'color': Tailwind.indigo500},
  {'name': 'Mathematics Volume 2', 'icon': Icons.calculate, 'color': Tailwind.indigo600},
  {'name': 'Micro Biology', 'icon': Icons.biotech, 'color': Tailwind.teal600},
  {'name': 'Nutrition and Dietetics', 'icon': Icons.local_dining, 'color': Tailwind.orange600},
  {'name': 'Office Management & Typography', 'icon': Icons.business_center, 'color': Tailwind.slate500},
  {'name': 'Physical Education', 'icon': Icons.sports_basketball, 'color': Tailwind.orange500},
  {'name': 'Physics Volume 1', 'icon': Icons.lightbulb, 'color': Tailwind.yellow600},
  {'name': 'Physics Volume 2', 'icon': Icons.lightbulb, 'color': Tailwind.yellow700},
  {'name': 'Political Science', 'icon': Icons.gavel, 'color': Tailwind.indigo500},
  {'name': 'Statistics', 'icon': Icons.pie_chart, 'color': Tailwind.blue400},
  {'name': 'Tamil', 'icon': Icons.language, 'color': Tailwind.rose600},
  {'name': 'Textiles and Dress Designing', 'icon': Icons.checkroom, 'color': Tailwind.pink400},
  {'name': 'Zoology', 'icon': Icons.pets, 'color': Tailwind.green700},
];
